name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.6'
      
    - name: Test mdBook
      run: mdbook test

  Spellcheck:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Update
      run: sudo apt update
    
    - name: Install aspell
      run: sudo apt install aspell -y
      
    - name: Run spellchecker
      run: ./ci/spellcheck.sh list
