name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.6'
      
    - name: Test mdBook
      run: mdbook test

    - name: Install aspell
      run: sudo apt update && sudo install aspell -y
      
    - name: Run spellchecker
      run: ./ci/spellcheck.sh list
